"""creates category table

Revision ID: 289d508933e1
Revises: bb4b240e83dc
Create Date: 2024-06-11 12:02:58.420833

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '289d508933e1'
down_revision = 'bb4b240e83dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category_name', sa.String(), nullable=False),
    sa.Column('equipment_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipments.id'], name=op.f('fk_categories_equipment_id_equipments')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('categories')
    # ### end Alembic commands ###
