"""drops make column from equipment

Revision ID: 325c5f7d8f3d
Revises: a2c75a0bb8cf
Create Date: 2024-06-19 16:08:28.278148

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '325c5f7d8f3d'
down_revision = 'a2c75a0bb8cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('equipments', schema=None) as batch_op:
        batch_op.drop_column('make')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('equipments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('make', sa.VARCHAR(), nullable=True))

    # ### end Alembic commands ###
