"""removes is_owner from users table

Revision ID: 6bf279969672
Revises: 2766887655d9
Create Date: 2024-06-09 16:30:24.643273

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6bf279969672'
down_revision = '2766887655d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('is_owner')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_owner', sa.BOOLEAN(), nullable=True))

    # ### end Alembic commands ###
