"""add start_date and end_date to Rental table. Changes Rent to Rental

Revision ID: a2c75a0bb8cf
Revises: aed8f7990507
Create Date: 2024-06-19 12:23:41.524338

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a2c75a0bb8cf'
down_revision = 'aed8f7990507'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rentals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('equipment_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipments.id'], name=op.f('fk_rentals_equipment_id_equipments')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_rentals_user_id_users')),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('rents')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rents',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('location', sa.VARCHAR(), nullable=True),
    sa.Column('date_time', sa.DATETIME(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('equipment_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipments.id'], name='fk_rents_equipment_id_equipments'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_rents_user_id_users'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('rentals')
    # ### end Alembic commands ###
