"""adds category_id to equipments table

Revision ID: aed8f7990507
Revises: 7e9b52afb643
Create Date: 2024-06-11 16:11:03.429116

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aed8f7990507'
down_revision = '7e9b52afb643'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.drop_constraint('fk_categories_equipment_id_equipments', type_='foreignkey')
        batch_op.drop_column('equipment_id')

    with op.batch_alter_table('equipments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(batch_op.f('fk_equipments_category_id_categories'), 'categories', ['category_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('equipments', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_equipments_category_id_categories'), type_='foreignkey')
        batch_op.drop_column('category_id')

    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('equipment_id', sa.INTEGER(), nullable=False))
        batch_op.create_foreign_key('fk_categories_equipment_id_equipments', 'equipments', ['equipment_id'], ['id'])

    # ### end Alembic commands ###
