"""changed owner_id to user_id in equipments route

Revision ID: fc9c742ef8aa
Revises: 6bf279969672
Create Date: 2024-06-10 14:07:44.626223

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc9c742ef8aa'
down_revision = '6bf279969672'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('equipments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint('fk_equipments_owner_id_users', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_equipments_user_id_users'), 'users', ['user_id'], ['id'])
        batch_op.drop_column('owner_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('equipments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('owner_id', sa.INTEGER(), nullable=False))
        batch_op.drop_constraint(batch_op.f('fk_equipments_user_id_users'), type_='foreignkey')
        batch_op.create_foreign_key('fk_equipments_owner_id_users', 'users', ['owner_id'], ['id'])
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
